server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: products
          uri: lb://products-service
          predicates:
            - Path=/api/products/**

        - id: orders
          uri: lb://orders-service
          predicates:
            - Path=/api/orders/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
