server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: products
          uri: lb://product-service
          predicates:
            - Path=/api/products/**

        - id: orders
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**

        - id: payments
          uri: lb://payment-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
